export interface PopularTicker {
  ticker: string;
  name: string;
}

export const POPULAR_TICKERS: PopularTicker[] = [
  { ticker: 'AAPL', name: 'Apple Inc.' },
  { ticker: 'MSFT', name: 'Microsoft Corporation' },
  { ticker: 'NVDA', name: 'NVIDIA Corporation' },
  { ticker: 'GOOGL', name: 'Alphabet Inc. Class A (Google)' },
  { ticker: 'GOOG', name: 'Alphabet Inc. Class C (Google)' },
  { ticker: 'AMZN', name: 'Amazon.com, Inc.' },
  { ticker: 'META', name: 'Meta Platforms, Inc. (Facebook)' },
  { ticker: 'TSLA', name: 'Tesla, Inc.' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway Inc. Class B' },
  { ticker: 'BRK.A', name: 'Berkshire Hathaway Inc. Class A' },
  { ticker: 'LLY', name: 'Eli Lilly and Company' },
  { ticker: 'V', name: 'Visa Inc.' },
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.' },
  { ticker: 'UNH', name: 'UnitedHealth Group Incorporated' },
  { ticker: 'XOM', name: 'Exxon Mobil Corporation' },
  { ticker: 'WMT', name: 'Walmart Inc.' },
  { ticker: 'MA', name: 'Mastercard Incorporated' },
  { ticker: 'PG', name: 'Procter & Gamble Company' },
  { ticker: 'JNJ', name: 'Johnson & Johnson' },
  { ticker: 'HD', name: 'Home Depot, Inc.' },
  { ticker: 'COST', name: 'Costco Wholesale Corporation' },
  { ticker: 'ORCL', name: 'Oracle Corporation' },
  { ticker: 'AVGO', name: 'Broadcom Inc.' },
  { ticker: 'NFLX', name: 'Netflix, Inc.' },
  { ticker: 'BAC', name: 'Bank of America Corporation' },
  { ticker: 'CRM', name: 'Salesforce, Inc.' },
  { ticker: 'KO', name: 'Coca-Cola Company' },
  { ticker: 'PEP', name: 'PepsiCo, Inc.' },
  { ticker: 'ADBE', name: 'Adobe Inc.' },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific Inc.' },
  { ticker: 'CSCO', name: 'Cisco Systems, Inc.' },
  { ticker: 'ABBV', name: 'AbbVie Inc.' },
  { ticker: 'MRK', name: 'Merck & Co., Inc.' },
  { ticker: 'AMD', name: 'Advanced Micro Devices, Inc.' },
  { ticker: 'ACN', name: 'Accenture plc' },
  { ticker: 'LIN', name: 'Linde plc' },
  { ticker: 'MCD', name: "McDonald's Corporation" },
  { ticker: 'CVX', name: 'Chevron Corporation' },
  { ticker: 'WFC', name: 'Wells Fargo & Company' },
  { ticker: 'ABT', name: 'Abbott Laboratories' },
  { ticker: 'DIS', name: 'Walt Disney Company' },
  { ticker: 'INTC', name: 'Intel Corporation' },
  { ticker: 'IBM', name: 'International Business Machines Corporation' },
  { ticker: 'QCOM', name: 'Qualcomm Incorporated' },
  { ticker: 'CAT', name: 'Caterpillar Inc.' },
  { ticker: 'TXN', name: 'Texas Instruments Incorporated' },
  { ticker: 'GE', name: 'General Electric Company' },
  { ticker: 'AMAT', name: 'Applied Materials, Inc.' },
  { ticker: 'NOW', name: 'ServiceNow, Inc.' },
  { ticker: 'AXP', name: 'American Express Company' },
  { ticker: 'GS', name: 'Goldman Sachs Group, Inc.' },
  { ticker: 'MS', name: 'Morgan Stanley' },
  { ticker: 'BLK', name: 'BlackRock, Inc.' },
  { ticker: 'BKNG', name: 'Booking Holdings Inc.' },
  { ticker: 'PFE', name: 'Pfizer Inc.' },
  { ticker: 'DHR', name: 'Danaher Corporation' },
  { ticker: 'PM', name: 'Philip Morris International Inc.' },
  { ticker: 'NEE', name: 'NextEra Energy, Inc.' },
  { ticker: 'UNP', name: 'Union Pacific Corporation' },
  { ticker: 'LOW', name: "Lowe's Companies, Inc." },
  { ticker: 'RTX', name: 'RTX Corporation (Raytheon)' },
  { ticker: 'HON', name: 'Honeywell International Inc.' },
  { ticker: 'BA', name: 'Boeing Company' },
  { ticker: 'SBUX', name: 'Starbucks Corporation' },
  { ticker: 'PYPL', name: 'PayPal Holdings, Inc.' },
  { ticker: 'UBER', name: 'Uber Technologies, Inc.' },
  { ticker: 'SHOP', name: 'Shopify Inc.' },
  { ticker: 'SNAP', name: 'Snap Inc. (Snapchat)' },
  { ticker: 'SQ', name: 'Block, Inc. (Square)' },
  { ticker: 'COIN', name: 'Coinbase Global, Inc.' },
  { ticker: 'PLTR', name: 'Palantir Technologies Inc.' },
  { ticker: 'ABNB', name: 'Airbnb, Inc.' },
  { ticker: 'F', name: 'Ford Motor Company' },
  { ticker: 'GM', name: 'General Motors Company' },
  { ticker: 'RIVN', name: 'Rivian Automotive, Inc.' },
  { ticker: 'NKE', name: 'Nike, Inc.' },
  { ticker: 'TGT', name: 'Target Corporation' },
  { ticker: 'T', name: 'AT&T Inc.' },
  { ticker: 'VZ', name: 'Verizon Communications Inc.' },
  { ticker: 'TMUS', name: 'T-Mobile US, Inc.' },
  { ticker: 'CMCSA', name: 'Comcast Corporation' },
  { ticker: 'INTU', name: 'Intuit Inc.' },
  { ticker: 'ISRG', name: 'Intuitive Surgical, Inc.' },
  { ticker: 'PANW', name: 'Palo Alto Networks, Inc.' },
  { ticker: 'CRWD', name: 'CrowdStrike Holdings, Inc.' },
  { ticker: 'SNOW', name: 'Snowflake Inc.' },
  { ticker: 'DDOG', name: 'Datadog, Inc.' },
  { ticker: 'MDB', name: 'MongoDB, Inc.' },
  { ticker: 'NET', name: 'Cloudflare, Inc.' },
  { ticker: 'ZS', name: 'Zscaler, Inc.' },
  { ticker: 'MU', name: 'Micron Technology, Inc.' },
  { ticker: 'LRCX', name: 'Lam Research Corporation' },
  { ticker: 'KLAC', name: 'KLA Corporation' },
  { ticker: 'ASML', name: 'ASML Holding N.V.' },
  { ticker: 'TSM', name: 'Taiwan Semiconductor Manufacturing Company' },
  { ticker: 'SMCI', name: 'Super Micro Computer, Inc.' },
  { ticker: 'ARM', name: 'Arm Holdings plc' },
  { ticker: 'BABA', name: 'Alibaba Group Holding Limited' },
  { ticker: 'JD', name: 'JD.com, Inc.' },
  { ticker: 'PDD', name: 'PDD Holdings Inc.' },
  { ticker: 'NIO', name: 'NIO Inc.' },
  { ticker: 'BYDDY', name: 'BYD Company Limited' },
  { ticker: 'NVO', name: 'Novo Nordisk A/S (Ozempic)' },
  { ticker: 'SPOT', name: 'Spotify Technology S.A.' },
  { ticker: 'DASH', name: 'DoorDash, Inc.' },
  { ticker: 'LYFT', name: 'Lyft, Inc.' },
  { ticker: 'PINS', name: 'Pinterest, Inc.' },
  { ticker: 'ROKU', name: 'Roku, Inc.' },
  { ticker: 'EA', name: 'Electronic Arts Inc.' },
  { ticker: 'TTWO', name: 'Take-Two Interactive Software, Inc.' },
  { ticker: 'RBLX', name: 'Roblox Corporation' },
];
